# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
includes_dir: ./_includes

# Handling Reading
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Plugins
gems: ['jekyll-sitemap','jekyll-feed','jekyll/scholar','pygments.rb','jekyll-email-protect']

# Conversion
markdown: kramdown
highlighter: pygments

# Markdown Processors
kramdown:  
  input: GFM
  syntax_highlighter: pygments

# Serving
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# Outputting
permalink: /:categories/:year/:title/

# Personal information
url: http://hoanganhduc.github.io
author: Hoàng Anh Đức
title: Welcome to Đức's personal webpage!
email_personal_user: anhduc.hoang1990
email_personal_domain: gmail.com
email_work_user: hoanganhduc
email_work_domain: jaist.ac.jp
website: hoanganhduc.github.io
website_full: http://hoanganhduc.github.io
keywords: Duc A. Hoang, JAIST, anhduc.hoang1990, hoanganhduc, personal webpage
skype: anhduc1990
institute_address: Japan Advanced Institute of Science and Technology (JAIST)
institute_postcode: 923-1292
institute_city:  1-1 Asahidai, Nomi, Ishikawa
institute_country: Japan

# Exclude files
exclude: ['Gemfile*','Makefile','Curriculum Vitae','*.bat','*.csl','exclude_copy*']

# Jekyll-scholar configuration
scholar:
  style: springer-lncs
  locale: en

  sort_by: year
  order: asscending
  bibliography_list_tag: ol

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{ reference }}"

  replace_strings: true
  join_strings:    true
  
  reference_tagname: div

  use_raw_bibtex_entry: true
  bibtex_filters:
  - superscript
  - latex

  query: "@*"
