# Site settings
title: Advanced Data Analytics in Science and Engineering Group at Skoltech
description: >
  The Advanced Data Analytics in Science and Engineering Group is a research
  organisation focused on the development of novel machine learning methods
  with industrial applications based at the Skolkovo Institute of Science and Technology (Skoltech)
user_title: Advanced Data Analytics in Science and Engineering Group at Skoltech, Moscow, Russia
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: ADASE
username_full: Advanced Data Analytics in Science and Engineering Group
user_description: >
  The Advanced Data Analytics in Science and Engineering Group is a research
  organisation focused on the development of novel machine learning methods
  with industrial applications based at the Skolkovo Institute of Science and Technology (Skoltech). 
  The group is conformed by a research team consisting of academic experts, doctoral students and developers.
user_title: Skoltech, Moscow, Russia
email: adase@skoltech.ru
twitter_username: adase
github_username:  adasegroup

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

about_title: ADASE
news_title: News
research_title: Research Agenda
industry_title: Industry Projects
teaching_title: Teaching
group_title: Research Group
staff_title: Staff
publications_title: Publications


block1_title: Modelling with Surrogate Functions
block2_title: Processing of 3D data
block3_title: Processing of online data

block1_description: Prediction systems with kernel methods such as engineering problems with surrogate functions.
block2_description: Processing 3D data in the areas of computer vision, brain image processing, chemoinformatics.
block3_description: Processing of online data such as anomaly detection, forecasting, change point detection, time series.

research_description: >
  ADASE is a group of research enthusiasts pushing the state of the art at the intersection of kernel methods 3D data, 
  deep learning, online data, and machine learning. Our research mission is to construct data-driven (surrogate) models capable of predicting behavior, 
  performing model-based control and recommend future actions, optimizing design and performance and detecting anomalies and predict failures. Aside from traditional convex and non-convex optimization techniques, 
  we see great potential in modern artificial intelligence, mainly deep learning, 
  in order to achieve these goals. 
  Keywords - Machine Learning, Engineering Problems, Online Data, Kernel Methods, Gaussian Process, Deep Learning.
  
staff_description: >
  Since 2016 Evgeny Burnaev works as Associate Professor of Skoltech Center for Computational Data-Intensive Science and Engineering. 
  Today, Evgeny’s research interests encompass the areas of regression based on Gaussian processes and kernel methods for multi-fidelity surrogate modeling and optimization, 
  Deep Learning for 3D Data Analysis and manifold learning, on-line sequence learning for prediction and non-parametric anomaly detection. 
  The main aim is development of new machine learning methods and their use for solution of applied engineering problems.

publications_description: Many publications coming soon

teaching_description: Many courses coming soon

# Resume settings
resume_avatar: "true"


# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
#name: Your Name
#email: you@example.com
#description: > # this means to ignore newlines until "url:"
#  A simple, whitespace theme for academics. Based on [*folio](https://github.com/bogoli/-folio) design.
footer_text: >
  Skoltech, Moscow, Russia
#url:  # the base hostname & protocol for your site
#baseurl: /al-folio # the subpath of your site, e.g. /blog/
#last_updated: # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
#github_username: # put your github username
#twitter_username: # put your twitter username
#linkedin_username: # put your linkedin username
#scholar_authorid: # put your google scholar author id
#contact_note: >
#  You can even add a little note about which of these is the best way to reach you.

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
#blog_name: al-folio
#blog_description: a simple whitespace theme for academics

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: adase # put your disqus shortname

# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  lectures:
    defaults:
      layout: post
    output: true
    permalink: /lectures/:path/
  projects:
    output: true
    permalink: /projects/:path/
    
news_limit: 5
lectures_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes
include: ['_pages']

# Gems
gems:
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# Jekyll-Scholar
scholar:

  last_name: Einstein

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.7.1"
anchorjs_version: "3.2.2"
